---
- name: Ensure libvirt dir storage pool directories exist
  file:
    path: "{{ libvirt_pool.path }}"
    owner: "{{ libvirt_pool.owner | default(omit) }}"
    group: "{{ libvirt_pool.group | default(omit) }}"
    mode: "{{ libvirt_pool.mode | default(omit) }}"
    state: directory

- name: Ensure libvirt storage pools are defined
  virt_pool:
    name: "{{ libvirt_pool.name }}"
    command: define
    xml: "{{ libvirt_pool.xml | default(lookup('template', 'pool.xml.j2')) }}"

- name: Ensure libvirt storage pools are active
  virt_pool:
    name: "{{ libvirt_pool.name }}"
    state: active

- name: Ensure libvirt storage pools are started on boot
  virt_pool:
    name: "{{ libvirt_pool.name }}"
    autostart: yes
